# Generated by Django 3.0.3 on 2020-04-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_auto_20200421_1124'),
        ('editions', '0002_edition_productions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='organizers',
            field=models.ManyToManyField(to='productions.Organizer'),
        ),
    ]
