# Generated by Django 3.0.3 on 2020-04-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_auto_20200421_1124'),
        ('editions', '0003_auto_20200421_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.ManyToManyField(to='productions.Description')),
            ],
            options={
                'ordering': ('-modified_at',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sponsors',
        ),
        migrations.AlterField(
            model_name='edition',
            name='sponsors',
            field=models.ManyToManyField(to='editions.Sponsor'),
        ),
    ]
