# Generated by Django 3.0.3 on 2020-04-21 11:50

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_auto_20200421_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='place',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='description',
        ),
        migrations.AddField(
            model_name='edition',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
