# Generated by Django 3.0.3 on 2020-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_auto_20200421_1150'),
        ('editions', '0005_auto_20200421_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AlterField(
            model_name='edition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/media/'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='productions',
            field=models.ManyToManyField(blank=True, null=True, to='productions.Production'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, to='editions.Sponsor'),
        ),
    ]
