# Generated by Django 3.0.3 on 2020-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0011_auto_20200517_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
