# Generated by Django 3.0.3 on 2020-05-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0012_auto_20200517_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='pictures')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editions.Edition')),
            ],
            options={
                'ordering': ('-modified_at',),
                'abstract': False,
            },
        ),
    ]
