# Generated by Django 3.0.3 on 2020-05-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0013_editionpictures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EditionPictures',
            new_name='EditionPicture',
        ),
    ]
