# Generated by Django 3.0.3 on 2020-05-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0018_editionpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='productions',
        ),
    ]
