# Generated by Django 3.0.3 on 2020-05-24 18:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0019_remove_edition_productions'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='link_google_map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='edition',
            name='location',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
