# Generated by Django 3.0.3 on 2020-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0005_auto_20200421_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='files'),
        ),
    ]
