# Generated by Django 3.0.3 on 2020-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_auto_20200517_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='production_type',
            field=models.CharField(choices=[('1', 'Gráficos'), ('2', 'Música'), ('3', 'Demo'), ('4', 'Intro'), ('5', 'Pixel Art'), ('6', 'Wild')], default='1', max_length=2),
        ),
    ]
