# Generated by Django 3.0.3 on 2020-06-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0020_auto_20200524_2038'),
        ('productions', '0010_auto_20200607_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.Edition'),
        ),
    ]
