# Generated by Django 3.0.7 on 2020-12-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0011_production_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
