# Generated by Django 3.0.7 on 2021-01-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0012_auto_20201215_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
