# Generated by Django 3.0.7 on 2021-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0015_auto_20210129_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scener',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
