# Generated by Django 3.0.7 on 2021-01-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0016_auto_20210129_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenersgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
