# Generated by Django 3.1.6 on 2021-04-13 11:23

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0017_auto_20210129_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='filepath',
            field=models.FileField(upload_to='files', validators=[upload_validator.FileTypeValidator(allowed_types=['image/jpeg', 'image/png', 'application/x-amiga-disk-format'])]),
        ),
    ]
