# Generated by Django 3.1.6 on 2021-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0018_auto_20210413_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='filepath',
            field=models.FileField(upload_to='files'),
        ),
    ]
