# Generated by Django 3.2 on 2021-04-26 10:02

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0020_auto_20210413_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='filepath',
            field=models.FileField(upload_to='files', validators=[upload_validator.FileTypeValidator(allowed_types=['application/x-amiga-disk-format', 'application/octet-stream'])]),
        ),
    ]
