# Generated by Django 3.2 on 2021-04-26 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productions', '0022_auto_20210426_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='scener',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='production',
            name='filepath',
            field=models.FileField(upload_to='files', validators=[upload_validator.FileTypeValidator(allowed_types=['application/x-amiga-disk-format', 'application/octet-stream', 'image/jpeg', 'image/png', 'application/x-tar', 'application/x-adf', 'application/x-lha'])]),
        ),
    ]
