# Generated by Django 3.2 on 2021-04-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_auto_20210426_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='scener',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
