# Generated by Django 3.2 on 2021-04-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0027_alter_scener_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scener',
            name='avatar',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(), null=True, upload_to='avatars', width_field=models.PositiveIntegerField()),
        ),
    ]
