# Generated by Django 3.2 on 2021-04-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0028_alter_scener_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scener',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
